using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

/// <summary>프로젝트 소유 UIPrefabsSO.Custom 항목을 직접 실행 가능한 Unity 메뉴 코드로 동기화합니다.</summary>
public static class UIPrefabsCustomMenuGenerator
{
    public const string OutputPath = "Assets/Editor/ActionFitUIPrefabsGeneratedMenuItems.cs";

    private const string MenuRoot = "GameObject/>>>UI_Prefab/";
    private static bool _syncScheduled;

    [InitializeOnLoadMethod]
    private static void Initialize()
    {
        ScheduleSync();
    }

    /// <summary>현재 asset import 또는 GUI 처리가 끝난 뒤 Custom 메뉴 동기화를 예약합니다.</summary>
    public static void ScheduleSync()
    {
        if (_syncScheduled) return;

        _syncScheduled = true;
        EditorApplication.delayCall += SynchronizeDelayed;
    }

    /// <summary>선택 가능한 프로젝트 설정에서 generated 메뉴 코드를 갱신합니다.</summary>
    public static bool Synchronize()
    {
        UIPrefabsSO settings = UIPrefabsSettingsUtility.LoadExisting();
        string settingsPath = settings != null ? AssetDatabase.GetAssetPath(settings) : string.Empty;
        if (!settingsPath.StartsWith("Assets/", StringComparison.Ordinal)) settings = null;

        string source = BuildSource(settings, out int menuCount, out int skippedCount);
        bool outputExists = File.Exists(OutputPath);
        if (!outputExists && (settings == null || menuCount == 0)) return false;

        if (outputExists && string.Equals(File.ReadAllText(OutputPath), source, StringComparison.Ordinal))
        {
            return false;
        }

        EnsureEditorFolder();
        File.WriteAllText(OutputPath, source, new UTF8Encoding(false));
        AssetDatabase.ImportAsset(OutputPath, ImportAssetOptions.ForceUpdate);

        if (skippedCount > 0)
        {
            UnityEngine.Debug.LogWarning(
                $"[UIPrefabsCustomMenuGenerator] Skipped {skippedCount} invalid or duplicate Custom menu entries.");
        }

        return true;
    }

    /// <summary>테스트와 진단에서 사용할 deterministic generated 메뉴 source를 반환합니다.</summary>
    public static string BuildSource(UIPrefabsSO settings)
    {
        return BuildSource(settings, out _, out _);
    }

    private static void SynchronizeDelayed()
    {
        _syncScheduled = false;
        Synchronize();
    }

    private static string BuildSource(UIPrefabsSO settings, out int menuCount, out int skippedCount)
    {
        var entries = new List<GeneratedEntry>();
        var menuPaths = new HashSet<string>(StringComparer.Ordinal);
        skippedCount = 0;

        if (settings?.Custom != null)
        {
            foreach (UIPrefabsSO.Entry entry in settings.Custom)
            {
                if (!TryCreateEntry(entry, out GeneratedEntry generated) || !menuPaths.Add(generated.MenuPath))
                {
                    skippedCount++;
                    continue;
                }

                entries.Add(generated);
            }
        }

        menuCount = entries.Count;
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated>");
        source.AppendLine("// UIPrefabsSO.Custom에서 자동 생성됩니다. 직접 수정하지 마세요.");
        source.AppendLine("// </auto-generated>");
        source.AppendLine("using UnityEditor;");
        source.AppendLine();
        source.AppendLine("internal static class ActionFitUIPrefabsGeneratedMenuItems");
        source.AppendLine("{");

        for (int index = 0; index < entries.Count; index++)
        {
            GeneratedEntry entry = entries[index];
            string menuPath = EscapeLiteral(entry.MenuPath);
            string prefabGuid = EscapeLiteral(entry.PrefabGuid);
            source.AppendLine($"    [MenuItem(\"{menuPath}\", false, 20)]");
            source.AppendLine(
                $"    private static void Create{index}() => NewUIPrefabObject.InstantiateRegisteredPrefabByGuid(\"{prefabGuid}\");");
            source.AppendLine();
            source.AppendLine($"    [MenuItem(\"{menuPath}\", true)]");
            source.AppendLine(
                $"    private static bool Validate{index}() => NewUIPrefabObject.CanInstantiateUnderSelection();");
            if (index < entries.Count - 1) source.AppendLine();
        }

        source.AppendLine("}");
        return source.ToString();
    }

    private static bool TryCreateEntry(UIPrefabsSO.Entry entry, out GeneratedEntry generated)
    {
        generated = default;
        if (entry?.Prefab == null) return false;

        string prefabPath = AssetDatabase.GetAssetPath(entry.Prefab);
        string prefabGuid = AssetDatabase.AssetPathToGUID(prefabPath);
        if (string.IsNullOrEmpty(prefabPath) ||
            !prefabPath.EndsWith(".prefab", StringComparison.OrdinalIgnoreCase) ||
            string.IsNullOrEmpty(prefabGuid))
        {
            return false;
        }

        string label = string.IsNullOrWhiteSpace(entry.Label) ? entry.Prefab.name : entry.Label.Trim();
        string category = string.IsNullOrWhiteSpace(entry.Category) ? "Custom" : entry.Category.Trim();
        if (string.IsNullOrEmpty(label)) return false;

        generated = new GeneratedEntry(MenuRoot + category + "/" + label, prefabGuid);
        return true;
    }

    private static string EscapeLiteral(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t");
    }

    private static void EnsureEditorFolder()
    {
        if (!AssetDatabase.IsValidFolder("Assets/Editor"))
        {
            AssetDatabase.CreateFolder("Assets", "Editor");
        }
    }

    private readonly struct GeneratedEntry
    {
        public GeneratedEntry(string menuPath, string prefabGuid)
        {
            MenuPath = menuPath;
            PrefabGuid = prefabGuid;
        }

        public string MenuPath { get; }
        public string PrefabGuid { get; }
    }
}

[CustomEditor(typeof(UIPrefabsSO))]
internal sealed class UIPrefabsSOInspector : Editor
{
    public override void OnInspectorGUI()
    {
        if (DrawDefaultInspector()) UIPrefabsCustomMenuGenerator.ScheduleSync();
    }
}

internal sealed class UIPrefabsCustomMenuAssetPostprocessor : AssetPostprocessor
{
    private static void OnPostprocessAllAssets(
        string[] importedAssets,
        string[] deletedAssets,
        string[] movedAssets,
        string[] movedFromAssetPaths)
    {
        if (ContainsSettings(importedAssets) ||
            ContainsSettings(movedAssets) ||
            ContainsDeletedSettings(deletedAssets) ||
            ContainsDeletedSettings(movedFromAssetPaths))
        {
            UIPrefabsCustomMenuGenerator.ScheduleSync();
        }
    }

    private static bool ContainsSettings(string[] paths)
    {
        foreach (string path in paths)
        {
            if (AssetDatabase.GetMainAssetTypeAtPath(path) == typeof(UIPrefabsSO)) return true;
        }

        return false;
    }

    private static bool ContainsDeletedSettings(string[] paths)
    {
        foreach (string path in paths)
        {
            if (string.Equals(Path.GetFileName(path), "UIPrefabsSO.asset", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }
}
